repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: [--maxkb=500]
    -   id: debug-statements
    -   id: name-tests-test
        exclude: ^tests/.*

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    - id: black
      language_version: python3.11
      args: [--line-length=100]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    - id: mypy
      additional_dependencies: [types-requests, types-python-dateutil, types-PyYAML]
      args: [--config-file=mypy.ini]
      exclude: ^tests/.*

-   repo: local
    hooks:
    -   id: clang-format
        name: clang-format
        description: Format C/C++ code with clang-format
        entry: clang-format -i --style=file
        language: system
        types: [c, cpp, cuda]
        files: ".*\.(c|h|cpp|hpp|cu)$"

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v16.0.6'
    hooks:
    - id: clang-format
      types_or: [c, cpp, cuda]
      args: [--style=file, -i]

-   repo: https://github.com/doublify-org/pre-commit-cmake-format
    rev: v0.6.13
    hooks:
    - id: cmake-format
      args: [--in-place]

-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.34.0
    hooks:
    - id: markdownlint
      args: [--config=.markdownlint.json]
      additional_dependencies: ['markdownlint-cli2']

ci:
  autofix_commit_msg: "style: Auto-format code with pre-commit hooks"
  autofix_prs: true
  skip: ["clang-format"]  # Skip clang-format in CI as it's handled by the other hook
