version: '3.8'

# =============================================================================
# Configuration des réseaux
# =============================================================================
networks:
  openyolo_net:
    driver: bridge
    attachable: true

# =============================================================================
# Configuration des volumes
# =============================================================================
volumes:
  # Volume pour les données de l'application
  openyolo-data:
    name: ${COMPOSE_PROJECT_NAME:-openyolo}_data

  # Volume pour le socket X11
  x11-socket:
    name: ${COMPOSE_PROJECT_NAME:-openyolo}_x11_socket

  # Volume pour les fichiers temporaires X11
  x11-tmp:
    name: ${COMPOSE_PROJECT_NAME:-openyolo}_x11_tmp

  # Volume pour les logs
  openyolo-logs:
    name: ${COMPOSE_PROJECT_NAME:-openyolo}_logs

# =============================================================================
# Configuration des services
# =============================================================================
services:
  # Service Xvfb pour fournir un serveur X virtuel
  xvfb:
    build:
      context: .
      dockerfile: Dockerfile.xvfb
      args:
        - USER_UID=${UID:-1000}
        - USER_GID=${GID:-1000}
        - BUILDKIT_INLINE_CACHE=1
    container_name: ${COMPOSE_PROJECT_NAME:-openyolo}-xvfb
    hostname: ${COMPOSE_PROJECT_NAME:-openyolo}-xvfb
    environment:
      - DISPLAY=:99
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
      - USER_UID=${UID:-1000}
      - USER_GID=${GID:-1000}
      - USERNAME=developer
    volumes:
      - x11-socket:/tmp/.X11-unix
      - x11-tmp:/tmp
    networks:
      - openyolo_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "xdpyinfo", "-display", ":99.0"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Service principal OpenYolo
  openyolo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - BUILDKIT_INLINE_CACHE=1
    container_name: ${COMPOSE_PROJECT_NAME:-openyolo}-app
    hostname: ${COMPOSE_PROJECT_NAME:-openyolo}-app
    depends_on:
      xvfb:
        condition: service_healthy
    environment:
      # Configuration de base
      - DISPLAY=:99
      - UID=${UID:-1000}
      - GID=${GID:-1000}
      - USERNAME=developer
      
      # Configuration X11
      - XAUTHORITY=/tmp/.Xauthority
      - XDG_RUNTIME_DIR=/tmp/runtime-dev
      
      # Configuration de débogage
      - G_MESSAGES_DEBUG=${G_MESSAGES_DEBUG:-all}
      - G_DEBUG=${G_DEBUG:-fatal-warnings}
      - DEBUG=${DEBUG:-0}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # Configuration de l'application
      - APP_NAME=OpenYolo
      - APP_HOME=/workspace
      
      # Configuration GTK
      - GTK_THEME=Adwaita
      - GDK_BACKEND=x11
      - CLUTTER_BACKEND=x11
      - NO_AT_BRIDGE=1
    volumes:
      - .:/workspace
      - x11-socket:/tmp/.X11-unix:ro
      - openyolo-data:/home/developer/.local/share/openyolo
      - openyolo-logs:/var/log/openyolo
    working_dir: /workspace
    # Options de terminal
    tty: true
    stdin_open: true
    # Configuration des privilèges
    privileged: true
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    # Configuration des périphériques
    devices:
      - /dev/dri:/dev/dri
      - /dev/input:/dev/input
    # Configuration réseau
    networks:
      - openyolo_net
    # Politique de redémarrage
    restart: unless-stopped
